import React from "react";

const Instruction = () => {
    return (
        <div>
            <ul>
                <li>Paste the link to be truncated or shortened in the input field.</li>
                <li>Clik the Short button.</li>
                <li>Copy the link generated by clicking the copy button</li>
            </ul>
        </div>
    );
};

export default Instruction;